# Generated by Django 2.2.11 on 2020-07-13 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cluster',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.Community'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('cluster', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together={('community', 'code')},
        ),
    ]
