# Generated by Django 2.2.11 on 2020-09-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_communitysetting_jobsetting'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='failure',
            index=models.Index(fields=['community_id', 'cluster_id', 'type', 'program_id', 'unit_id', 'detected', 'closed'], name='monitoring__communi_c483b1_idx'),
        ),
    ]
